# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "127.0.0.1:3306"
my_user = "root"
my_pass = ""

# Elasticsearch address
es_addr = "127.0.0.1:9200"

# Path to store data, like master.info, and dump MySQL data 
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave 
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
mysqldump = "mysqldump"

# MySQL data source
[[source]]
schema = "test"

# Only below tables will be synced into Elasticsearch.
# "test_river_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
tables = ["test_river", "test_river_[0-9]{4}"]

# Below is for special rule mapping
[[rule]]
schema = "test"
table = "test_river"
index = "river"
type = "river"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    [[rule.fields]]
    mysql = "title"
    elastic = "es_title"

    [[rule.fields]]
    mysql = "tags"
    elastic = "tags"
    type = "list"

# wildcard table rule, the wildcard table must be in source tables 
[[rule]]
schema = "test"
table = "test_river_[0-9]{4}"
index = "river"
type = "river"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    [[rule.fields]]
    mysql = "title"
    elastic = "es_title"


